steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$_IMAGE_TAG',
    '-f',
    'dockerfiles/vertex_train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$_IMAGE_TAG'
  ]
substitutions:
  _REPO_NAME: mlops-training
  _IMAGE_NAME: mlops-trainer
  _IMAGE_TAG: v1
options:
  logging: CLOUD_LOGGING_ONLY