logging:
  level: INFO

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,reports/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}}
  sweep:
    dir: ${oc.env:OUTPUT_DIR,reports/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}}
    subdir: ${hydra.job.num}
  job:
    chdir: false
